apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: hotelManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          ports:
            - containerPort: 8083
              env:
            - name: SPRING_ELASTICSEARCH_URIS
              value: "http://elasticsearch:9200"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
              value: "http://eureka-server:8761/eureka/"