apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: hotel-management
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: NodePort