apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: hotelManagement
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort