apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: hotel-management
spec:
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort