apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
  namespace: hotel-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
        - name: hotel-service
          imagePullPolicy: Never
          image: hotel-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongo:27017/hotel-db"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
              value: "http://eureka-server:8761/eureka/"