apiVersion: v1
kind: Service
metadata:
  name: hotel-service
  namespace: hotelManagement
spec:
  selector:
    app: hotel-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: NodePort